<?php if ($this->pageCount <= 1) { return; } ?>
<div  class="pagination-item">
<ul class="pagination<?php if (!empty($class)) { echo ' ' . $class; } ?>">
    <!-- First page link -->
    <?php if ($this->previous) { ?>
    <li><a href="<?php echo $this->first->url; ?>"><?php _e('صفحه اول'); ?></a>
    <?php } ?>
    <!-- Previous page link -->
    <?php if ($this->previous) { ?>
    <li><a href="<?php echo $this->previous->url; ?>"><?php _e('&lt; قبلی'); ?></a>
    <?php } ?>
    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
    <li class="<?php echo ($page->number == $this->current) ? 'active' : ''; ?>">
        <a href="<?php echo $page->url; ?>"><?php echo _number($page->number); ?></a>
    </li>    
    <?php endforeach; ?>
    <?php if ($this->next) { ?>
    <!-- Next page link -->
    <li><a href="<?php echo $this->next->url; ?>"><?php _e('بعدی &gt;'); ?></a>
    <?php } ?>
    <!-- Last page link -->
    <?php if ($this->next) { ?>
     <li><a href="<?php echo $this->last->url; ?>"><?php _e('صفحه آخر'); ?></a>
    <?php } ?>
</ul>
</div>